language: julia
julia:
  - 1.0
os:
  - linux
  - osx
coveralls: true
notifications:
  email: true

# coveralls: true
after_success:
  - julia -e 'cd(Pkg.dir("Robotics")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())';
